spring:
    application:
        name: basic-pj

    datasource:
        url: jdbc:mariadb://localhost:3306/basicpj_db
        username: root
        password: mariadb1234
        driver-class-name: org.mariadb.jdbc.Driver

    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp

mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: org.example.basicpj.domain

server:
    port: 8080

logging:
    level:
        org.springframework: INFO